---
branches:
  - pm4
  -
projects:
  skin-factory-pm4:
    model: virion
    type: library
    lint:
      phpstan: false
    libs:
      - src: PresentKim/png-converter/png-converter-pm4
        version: ^1.0.3
...
